---
title: "data"
output: html_document
---

This script imports ACS 5 year estimates on preschool enrollment.

Note "School" includes both private and public schools.

```{r}
library(dplyr)

year <- 2021
county_of_interest <- '23005' 
state_of_interest <- '23'

codebook <- tidycensus::load_variables(2021, "acs5", cache = TRUE) %>% 
  filter(
    concept == 'SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER',
     grepl("3 and 4 years",label)
    ) %>% 
  select(name, label)
print(codebook)

```

```{r}
variables <- c(
  'Enrolled in preschool' = 'B14003_004', # Male
  'Enrolled in preschool' = 'B14003_013', # Male
  'Not enrolled in preschool' = 'B14003_022', # Male
  'Enrolled in preschool' = 'B14003_032', # Female
  'Enrolled in preschool' = 'B14003_041', # Female
  'Not enrolled in preschool' = 'B14003_050' # Female
)


states <- tigris::states() %>% 
  sf::st_drop_geometry() 

# Import ACS Data
acs_county <- tidycensus::get_acs(
  geography = "county",
  variables = variables,
  county = states$GEOID,
  year = year,
  survey = "acs5",
  cache_table = TRUE
) %>% 
  filter(GEOID == county_of_interest)

acs_state <- tidycensus::get_acs(
  geography = "state",
  variables = variables,
  state = state_of_interest,
  year = year,
  survey = "acs5",
  cache_table = TRUE
)

acs_us <- tidycensus::get_acs(
  geography = "us",
  variables = variables,
  year = year,
  survey = "acs5",
  cache_table = TRUE
)

combined <- bind_rows(acs_county, acs_state, acs_us) %>% 
  group_by(NAME, GEOID, variable) %>%
  summarise(estimate = sum(estimate, na.rm = TRUE)) %>%
  tidyr::pivot_wider(
    names_from = 'variable',
    values_from = 'estimate'
  )

out <- combined %>% 
  mutate(
    `Total preschool age children` = `Enrolled in preschool` + `Not enrolled in preschool`,
    `Share enrolled in preschool` = `Enrolled in preschool` / `Total preschool age children`,
    NAME = gsub("\\,.*", "", NAME)
  ) 


knitr::kable(out)
```